language: node_js
node_js: '9.2.1'
cache:
  directories:
  - node_modules
  - web/node_modules
stages:
  - lint
  - build
  - deploy
jobs:
  include:
  - stage: lint
    script: cd web && yarn install && yarn lint
  - stage: build
    script: cd web && yarn install && yarn build
  - stage: deploy
    script: skip
    deploy: &heroku
      - provider: heroku
        app: iibu-dev
        api_key:
          secure: "c5AMxiQaOQwDMtH3x0U7x9U3QbSkvtND9/CHsz5aoosNwo90GcoALfNy4rKeVF/VT1qLFwrfOomYuc9EB0b9vBXY2+wQjGQUzntw6j6TIPJ51TW950A0Pzs1b7Ihp2bvK3rbe1Uzv4Cp6SkOOC8Puo6V/q2AfVnnkqugXKuPssx8UFbvY/0ftFz8nyGCOHIyNIKO/OfhAYBIAt9MmWhLDSar87OkzN0C0yZFnUmbIXofPVvmoMZ5cAT59CjtncUJF+/9f5N+UzH93onb4QQb9gwrf5UVYniDLLgp0UAF/K0/yIdT1wSy6U6AW8uMDcKn0XFs1dJWsIHP21YTQP0hZ8DXP3Bb/1mBvL6rDFqcUWc57uA2vUEKzJ4UCPcjSxXysNlJicjHTpCvvn3uW7XaObOaIJGWY8AuyN0nvnLYF2vVMxnQXHgD/ph0yS7FXnMv4r9VIiAqwRmtPpaJFRpcGRxw8naVW2KWRLYpRkg1Eq5W2nv9fVC8QhzBkEFFwJMyCY3vh5zMDKIZTNLt3NvcdJgjbMtUzW2Ahc8Ngs8xUm84BiHAKJLwdDarcv5r1Jk75t3lyAvV7BGhPPGpFH4jJoSc7LtGfbOCkIEnWZEh1WtjXWAjixCFKlSy0sgWS4eG5rW8KxHmbN6V7HpoIMKdHBeoW02GgKvKOKztP6UcMNo="
        on:
          tags: false
      - provider: heroku
        app: iibu
        api_key:
          secure: "c5AMxiQaOQwDMtH3x0U7x9U3QbSkvtND9/CHsz5aoosNwo90GcoALfNy4rKeVF/VT1qLFwrfOomYuc9EB0b9vBXY2+wQjGQUzntw6j6TIPJ51TW950A0Pzs1b7Ihp2bvK3rbe1Uzv4Cp6SkOOC8Puo6V/q2AfVnnkqugXKuPssx8UFbvY/0ftFz8nyGCOHIyNIKO/OfhAYBIAt9MmWhLDSar87OkzN0C0yZFnUmbIXofPVvmoMZ5cAT59CjtncUJF+/9f5N+UzH93onb4QQb9gwrf5UVYniDLLgp0UAF/K0/yIdT1wSy6U6AW8uMDcKn0XFs1dJWsIHP21YTQP0hZ8DXP3Bb/1mBvL6rDFqcUWc57uA2vUEKzJ4UCPcjSxXysNlJicjHTpCvvn3uW7XaObOaIJGWY8AuyN0nvnLYF2vVMxnQXHgD/ph0yS7FXnMv4r9VIiAqwRmtPpaJFRpcGRxw8naVW2KWRLYpRkg1Eq5W2nv9fVC8QhzBkEFFwJMyCY3vh5zMDKIZTNLt3NvcdJgjbMtUzW2Ahc8Ngs8xUm84BiHAKJLwdDarcv5r1Jk75t3lyAvV7BGhPPGpFH4jJoSc7LtGfbOCkIEnWZEh1WtjXWAjixCFKlSy0sgWS4eG5rW8KxHmbN6V7HpoIMKdHBeoW02GgKvKOKztP6UcMNo="
        on:
          tags: true
