env:
  browser: true
  es6: true
  jest: true
  node: true
extends: 'airbnb'
root: true
plugins:
  - import
  - node
  - react
parser: babel-eslint
settings:
  import/resolver:
    node:
      moduleDirectory:
        - node_modules
        - src
